### ISSUE TITLE
Multi Translator extension - Feedback/Bug reports

### ISSUE THREAD

**Issue by Odyseus** [Odyseus/CinnamonTools#25]
## Extension status

- Extension ready to be translated.
- Extension [published on the Spices repository](https://github.com/linuxmint/cinnamon-spices-extensions/pull/26) to be reviewed on **March 18, 2017**.

The Multi Translator extension is an extension ported from a gnome-shell extension called [Text Translator](https://github.com/gufoe/text-translator) by [gufoe](https://github.com/gufoe).

## Differences with the original extension

* [x] Removed instant translation and auto-speak options to avoid translation service *abuse*.
* [x] Themable interface.
* [x] ~Migrated to Cinnamon's native settings system.~ Came back to a custom settings window.
* [x] Unified all .js files into just one.
* [x] Obvious needed changes like changing all gnome-shell APIs usage to Cinnamon's, changed the use of JavaScript classes to prototypes, etc.

## Dependencies

**If one or more of these dependencies are missing in your system, you will not be able to use this extension.**

- **xsel** command: XSel is a command-line program for getting and setting the contents of the X selection.
- **trans** command: Command provided by the package translate-shell. Is a simple command line interface for several translation providers (Google Translate, Yandex Translate, Bing Translator and Apertium) which allows you to translate strings in your terminal.
    - Check translate-shell [dependencies](https://github.com/soimort/translate-shell#dependencies) and [recommended dependencies](https://github.com/soimort/translate-shell#recommended-dependencies).

**Note:** The translate-shell package available on Ubuntu 16.04.x/Linux Mint 18.x repositories is outdated and broken. It can be installed anyway so it will also install its dependencies. But updating to the latest version should be done as described bellow.

#### Option 1. Direct Download

This method will only install the trans script into the specified locations.

For the current user only. **~/.local/bin** needs to be in your PATH.
```shell
$ wget -O ~/.local/bin/trans git.io/trans && chmod ugo+rx ~/.local/bin/trans
```

For all users without overwriting the installed version.
```shell
$ sudo wget -O /usr/local/bin/trans git.io/trans && sudo chmod ugo+rx /usr/local/bin/trans
```

#### Option 2. From Git - [More details](https://github.com/soimort/translate-shell/blob/develop/README.md#option-3-from-git-recommended-for-seasoned-hackers)

This method will not just install the trans script but also its man pages. Refer to the link above for more installation details.

```shell
$ git clone https://github.com/soimort/translate-shell
$ cd translate-shell
$ make
$ sudo make install
```

## Extension usage

Once installed and enabled, the following shortcuts will be available.

#### Global shortcuts (configurable from the extension settings)

- **<kbd>Super</kbd> + <kbd>T</kbd>:** Open translator dialog.
- **<kbd>Super</kbd> + <kbd>Shift</kbd> + <kbd>T</kbd>:** Open translator dialog and translate text from clipboard.
- **<kbd>Super</kbd> + <kbd>Alt</kbd> + <kbd>T</kbd>:** Open translator dialog and translate from primary selection.

#### Shortcuts available on the translation dialog

- **<kbd>Ctrl</kbd> + <kbd>Enter</kbd>:** Translate text.
- **<kbd>Shift</kbd> + <kbd>Enter</kbd>:** Force text translation. Ignores translation history.
- **<kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>C</kbd>:** Copy translated text to clipboard.
- **<kbd>Ctrl</kbd> + <kbd>S</kbd>:** Swap languages.
- **<kbd>Ctrl</kbd> + <kbd>D</kbd>:** Reset languages to default.

## Tested environments

* [x] ![Cinnamon 2.8](https://odyseus.github.io/CinnamonTools/lib/badges/cinn-2.8.svg) ![Linux Mint 17.3](https://odyseus.github.io/CinnamonTools/lib/badges/lm-17.3.svg)
* [x] ![Cinnamon 3.0](https://odyseus.github.io/CinnamonTools/lib/badges/cinn-3.0.svg) ![Linux Mint 18](https://odyseus.github.io/CinnamonTools/lib/badges/lm-18.svg)
* [x] ![Cinnamon 3.2](https://odyseus.github.io/CinnamonTools/lib/badges/cinn-3.2.svg) ![Linux Mint 18.1](https://odyseus.github.io/CinnamonTools/lib/badges/lm-18.1.svg)

**Note on Cinnamon 2.8.x:** All issues on this version of Cinnamon are as fixed as they going to get. It's a complete nightmare working on this version of Cinnamon, so I simply gave up trying to fix the unfixable. My guess is that Cinnamon 2.8.x uses an *ultra-antique* version of GTK3 (3.10), and all APIs available on this version of GTK3 behave totally different than the APIs found on current versions of GTK3. Throughout the extension code it can be seen how I'm forced to use totally different Clutter elements depending on the version of Cinnamon that is used.

### Known issues

- Up until now, all known issues are aesthetics.
    1. ~~In Cinnamon 2.8.x, on small screen resolutions (1024x768), some elements at the bottom of the translation dialog are rendered outside the dialog itself. **Workaround:** Set the dialog to occupy more screen percentage (90% width and 70% height for example).~~ Fixed.
    2. ~~In Cinnamon 2.8.x, none of the elements inside the translation dialog are aligned how they are supposed to. **Workaround:** None. Working on it.~~ Fixed.
    3. ~~In Cinnamon 2.8.x, when some of the elements that auto-hide themselves are hidden/shown, all the elements inside the dialog start *dancing*. **Workaround:** None. Might be related to point **2**. Working on it.~~ Fixed.
    4. ~~In Cinnamon 3.0.x and 3.2.x, on small screen resolutions (1024x768) and using the Mint-Y theme, an element at the bottom of the translation dialog that doesn't belong to the dialog is rendered outside the dialog itself (Might be similar to point **1**). **Workaround:** Have no idea. Must be a bug with the Mint-Y themes family or it is visible simply because the Mint-Y themes set the background color for the **modal-dialog-button-box** class. The element displayed outside the dialog isn't even added by this extension, it's a button container that should be invisible if empty. But with the Mint-Y theme is visible even when empty.~~ Fixed.

### Multi Translator extension ToDo list:

* [x] **Test extension on all currently supported versions of Cinnamon**
* [x] **Switch back to a custom settings window** Cinnamon's native settings system is very practical, but it's also very limited. There are certain settings that can be modified in the gnome-shell extension (the extension Multi Translator is based on) that aren't possible to modify using Cinnamon's native settings system. So, I will give a try to a custom one.
* [x] **Add the possibility to select a custom theme**
* [x] **Add "Service provided by Service provider name" notice** This is needed to comply with the terms of use for the translation services.
* [x] **Implement a mechanism to check for dependencies**
* [x] **Provide alternate methods in case translate-shell breaks or doesn't exists (manually configurable or automatic)**
    - There are a total of 3 translation services that doesn't require translate-shell. For now, this should suffice.
* [x] **Add more translation providers that doesn't require the use of translate-shell**
    - Added another Google Translate method that makes use of the mechanism used by the Google Translate Chrome extension.
    - Added **Transltr** service. The only translation service on the face of the earth with a public API and that makes no use of API keys. Lets enjoy it while it lasts (LOL).
* [x] **Create the translation template**
* [x] **Add more translation providers:** At least as much as translate-shell supports.
* [x] **Add Yandex API keys configuration**
* [x] **Make Yandex API keys usage random**
* [x] **Implement translation history**
* [x] **Keep looking for a way to reload the themes without the need to restart Cinnamon** Keep in mind the comment block in extension.js>TranslatorExtension>_loadTheme().
* [x] **Create the dark Linux Mint theme**
* [x] **Add translation mechanism**
* [x] ~**Change all synchronous functions to asynchronous**~ Abandoned idea.
* [x] ~**Create a mechanism to display statistics**~ Abandoned idea.

##### Dialog translation images

![Translation dialog](https://odyseus.github.io/CinnamonTools/lib/img/MultiTranslatorExtension-001-trans-dialog.png)

[Source language selection](https://odyseus.github.io/CinnamonTools/lib/img/MultiTranslatorExtension-002-souce-lang-selection.png) - [Target language selection](https://odyseus.github.io/CinnamonTools/lib/img/MultiTranslatorExtension-003-target-lang-selection.png) - [Translation provider selection](https://odyseus.github.io/CinnamonTools/lib/img/MultiTranslatorExtension-004-trans-provider-selection.png) - [Main menu](https://odyseus.github.io/CinnamonTools/lib/img/MultiTranslatorExtension-005-main-menu.png) - [Quick help](https://odyseus.github.io/CinnamonTools/lib/img/MultiTranslatorExtension-006-quick-help.png)

##### Settings window image

![MultiTranslatorExtension-options](https://odyseus.github.io/CinnamonTools/lib/img/MultiTranslatorExtension-options.gif)

## Issue reports

**Issue reporters should adjunct the output of the following commands.**
**Check the content of the log files for sensible information BEFORE running the commands!!!**

`inxi -xxxSc0 -! 31`
`pastebin ~/.cinnamon/glass.log`
`pastebin ~/.xsession-errors`

**References to anyone that could be interested in testing the extension.**

@buzz @copecu @fortalezense @maladro1t @NikoKrause @pizzadude @Radek71 @sphh

**Comment by pizzadude** [comment]
I tried to load the extension, but it failed to load, and in the log it says 

"error t=2017-02-24T22:24:55.837Z [Applet "0dyseus@MultiTranslatorExtension"]: File not found: /home/pizzadude/.local/share/cinnamon/applets/0dyseus@MultiTranslatorExtension/applet.js"
error t=2017-02-24T22:24:55.837Z Could not load applet 0dyseus@MultiTranslatorExtension

**Comment by Odyseus** [comment]
@pizzadude: Remove it from were you installed it and place it in the right place. Cinnamon extensions aren't applets and applets aren't extensions.

**Comment by pizzadude** [comment]
..derp

**Comment by pizzadude** [comment]
It only works if you install the latest version of translate-shell, the one in the Ubuntu 16.04/Linux Mint 18.x repos is outdated.

git clone https://github.com/soimort/translate-shell
cd translate-shell/
make
sudo make install

**Comment by Odyseus** [comment]
Thanks for the feedback, @pizzadude.

I will add that information on the **Depedencies** section above along with other ways to install the latest version. And I think that it's needed to also specify the translate-shell dependencies.

**Comment by Odyseus** [comment]
### Fifth prototype changelog
- Some minor fixes on the themes' style sheets.
- Fixed a bug introduced by the implementation of "Detect language" as source language.
    - With Yandex as service provider, the target language chooser was empty.
    - With Google as service provider, the argument "auto" was passed to the **trans** script and interpreted as a text to be translated. That's why all translations showed the word *auto* (car) in the translation result. LOL
- First step on implementing translation history. It can be opened but the extension still doesn't save the translation results to it.
- Implemented a menu on the translator dialog that will allow me to add more direct access to certain settings without adding to much clutter.
- Updated the list of supported languages.

**Comment by Odyseus** [comment]
### Sixth prototype changelog

- Fixed style sheet unloading after switching a desktop theme.
- Translation history fully implemented.
- Added Yandex API key configuration and randomization of its usage.
- Better error reporting of Yandex usage.
- Added Bing and Apertium providers (dependent on translate-shell).
- Created localization template (**Do not start translations just yet**). I created it mainly to test the sorting of translated language names (BTW, the list of languages can be translated and sorted alphabetically and it works beautifully).
- Cleaned some unused code.

**Comment by Odyseus** [comment]
### Seventh prototype changelog

- Fixed broken translation triggers. Now it will normally trigger a translation when swapping languages, when trying to translate from clipboard/selection and when changing source/target languages.
- Changed all translation provider names that require translate-shell. They are now identified with a **TS** at the end.
- Fixed target text text-to-speech when attempting to *speak* an entry from the translation history.
- Fixed keybindings removal.
- Implemented check for dependencies mechanism.
- Added **Service provided by..** notice.
- Added **Transltr** service provider.
- Added an alternate Google Translate method that doesn't require translate-shell.
- Updated localization template.
- More code cleaning.

**Comment by Odyseus** [comment]
### Eighth prototype changelog

- Added custom theme selection.
- Some minor tweaks to all themes.
- Fixed a resizing issue on the language chooser dialogs.

**Comment by Odyseus** [comment]
### Nineth prototype changelog

**Completely remove any previous version of this extension before installing the new version.**

- Switched back to a custom settings window. Now it is possible to change every single extension setting.
    - Opted for a Python script instead of a JavaScript one.
    - Python script based on a settings script by [jferrao](https://github.com/jferrao) for his [All-in-one Places applet](https://github.com/jferrao/gtk) plus some JavaScript functions from the original extension Multi Translator is based on that were *translated* into Python.
- Updated help file with instruction to update to the latest translate-shell version.
- Fixed a resizing issue on the language chooser dialogs.

**Comment by Odyseus** [comment]
### Tenth prototype changelog

**Completely remove any previous version of this extension before installing the new version.**

- Finally fixed text alignment on the translation dialog top bar.
- Removed some leftovers from the past usage of Cinnamon's native settings system.
- Removed some more leftovers from the past usage of Gnome-shell's APIs.
- Finally managed to align the Quit/Help/Main menu buttons to the top-right corner of the translation dialog.
- Changed the way all internal imports are made.
- Now both popups inside the translation dialog (from the provider selector and the main menu) behave as they should.
    - Both popups will close when their respective buttons are pressed for a second time.
    - When the language choosers dialogs or the quick help dialog are opened, any opened popup will close automatically.
    - When the translation dialog is closed, no popup will stay open on screen.
- Now keybindings are updated correctly after changing any of them.
- Some tweaks and fixes to the theme's style sheets.
- Added icons to the translation providers popup.
- Added a missing translatable string.
- Preliminary tests on Cinnamon 3.2. All seems OK so far.

**Comment by Odyseus** [comment]
### Eleventh prototype changelog

**Completely remove any previous version of this extension before installing the new version.**

- Changed from individual buttons to a menu button on the preferences window to manage settings.
- Some grammatical corrections.
- Preliminary tests on Cinnamon 2.8. Everything seemed OK at first, but the elements inside the translation dialog were invisible. After a couple of tweaks to add retro-compatibility, everything seems to work as it should.

**Comment by Odyseus** [comment]
## Extension status

- Extension ready to be translated.
- Estimated date for publishing on the Spices website: **March 17, 2017**.

### Twelfth and last prototype changelog

**Completely remove any previous version of this extension before installing the new version.**

- Changed the function to get selection from synchronous to asynchronous.
- Enable the use of markup on the history window so the styling tags, if any, aren't displayed.
- Changed the use of **set_width/set_height** method to the use of **set_size** method. Curiously, this fixes some issues on Cinnamon 2.8.x.
- Some code clean up.
- Tested compatibility with several Cinnamon themes. See **Known issues**.
- Further tests on all supported Cinnamon versions (2.8, 3.0.x and 3.2.x).

**Comment by Odyseus** [comment]
### Thirteenth (probably last) prototype changelog

**Completely remove any previous version of this extension before installing the new version.**

- Redesigned custom setting window to have an appearance similar to the Cinnamon 3.2.x native settings system.
- Added some missing strings that need to be translated.

**Comment by sphh** [comment]
Hi,

Great work (as usual ;-) )! Thanks!

I found two issues, most likely again because I still use the Mint-X theme:

1. When clicking on the target language to change it, the following happens:
![screenshot from 2017-03-20 10-58-23](https://cloud.githubusercontent.com/assets/4856462/24098264/8b713b20-0d61-11e7-8a46-93fb5d185688.png)

2. When selecting a word to be translated and pressing `<Super><Alt>T`, only the last character of the word is selected:
![screenshot from 2017-03-20 11-19-11](https://cloud.githubusercontent.com/assets/4856462/24098307/b8e3aab6-0d61-11e7-8238-5d61dc0102cf.png)
When I close the Translator and press `<Super><Alt>T` again, the whole word is selected in the Translator.

I noticed both behaviours in the very first version, but was away and could not update the extension to check.

**Comment by Odyseus** [comment]
Hello, @sphh

Don't worry about the Mint-X theme. The extension dialog doesn't use nor it is affected by the current desktop theme. At least it shouldn't.

1. You will have to explain with words what's wrong in that image (I'm physically unable to see in detail dark themes). If it is the fact that the translated text can be seen behind the language selector dialog, then it's because it seems that I forgot to set a background color for that dialog on the default theme (the one used by the extension). I will fix it in next release.
    - If you want to fix it yourself in the meantime, open the file **0dyseus@MultiTranslatorExtension/themes/default.css** and edit this...

```css
.translator-language-chooser-box {
    border: 1px solid #8b8b8b;
    margin: 10px 0;
}
```

...to this...

```css
.translator-language-chooser-box {
    background-color: rgba(63, 63, 63, 0.95);
    border: 1px solid #8b8b8b;
    margin: 10px 0;
}
```

2. I saw that text selection issue too since the beginning. I forgot to take note of it then, so I forgot to fix it later. Already fixed for the next release.

Thank you very much for the feedback, sphh. :+1:

**Comment by sphh** [comment]
Hi @Odyseus 

Thank you for your quick response.

1. Yes, that's what I meant! And that additional line solved the problem.
2. Thanks.

BTW this extension cannot be found on [Cinnamon Spices](https://cinnamon-spices.linuxmint.com/extensions/latest) nor in the extension system setting dialog...

**Comment by Odyseus** [comment]
> BTW this extension cannot be found on Cinnamon Spices nor in the extension system setting dialog...

It is still [under review](https://github.com/linuxmint/cinnamon-spices-extensions/pull/26). It will take them some time because there are a lot of files and a lot more code.

**Comment by sphh** [comment]
Ah, yes, I forgot that "they" review spices nowadays...

**Comment by Odyseus** [comment]
Initial release published on Spices website. Open new issues to report bugs or feature requests.
